version: "3"
services:
  nuxt:
    image: node:14
    working_dir: "/var/www/app"
    environment:
      - HOST=0.0.0.0
    command: bash -c "npm install && npm run serve"
    volumes:
      - ./:/var/www/app
    ports:
    - "8080:8080"

